### ISSUE TITLE
Uncaught ReferenceError: FullCalendar is not defined

### ISSUE THREAD

**Issue by tomcodes** [acaronlex/laravel-calendar#20]
Hello!

First of all thank you for making an updated version of this package that I have been using for years. I am trying to convert an existing project to your new package and have the following error when I refresh the page where I have the full calendar:

`Uncaught ReferenceError: FullCalendar is not defined`

This line triggers this error (which is rendered by the `{!! $calendar->render() !!}` I guess):

`calendar = new FullCalendar.Calendar(calendarEl,`

I tried to follow [FullCalendar ES6 import method](https://fullcalendar.io/docs/initialize-es6) but could not manage to have it working.

Could you please confirm that the only working method for your package is to importe the script via <script> tags?

Thank you very much!

**Comment by Maurits-ten-Thije** [comment]
Hey there, currently trying to implement this in a new project of mine.

I'm also running into the same problem currently, did you find anyway to fix this issue?

Please let me know.

**Comment by seche** [comment]
Having the same issue when using ES6. 

For the newer version 5+ ofFullCalendar.io

Make sure to use this syntax with Script Tags and Browser Globals:

    var calendar = new FullCalendar.Calendar(calendarEl, {
      ...
    });

And with ES6 build system use this syntax:

    var calendar = new Calendar(calendarEl, {
      ...
    });

Basically the object FullCalendar is not available in ES6. BUT once I had that sorted out in the script.blade.php file, my options were breaking the calendar because the JSON object output into a javascript object isn't compatible. I had to add a function to strip double quotes from the keys to make it work.

I added this to the Calendar Class
```

/**
     * Replace keys with non-JSON encoded values
     *
     * @param $json
     * @return string
     */
    protected function replaceKeys($json)
    {
        $search  = [];
        $replace = [];

        // Stripping double quotes from plugins values
        foreach (json_decode($json) as $key => $value) {
            if(strtolower($key) === 'plugins'){
                foreach ($value as $key) {
                    $search[]  = '"' . $key . '"';
                    $replace[] = $key;
                }
            }
        }
        $json = str_replace($search, $replace, $json);
        
        return preg_replace('/"(.+)":/i', '${1}:', $json);

    }

```

Then in getOptionsJson (calendar.php) I changed this:

`$json = json_encode($parameters);`

to this:

`$json = $this->replaceKeys(json_encode($parameters, JSON_PRETTY_PRINT));`


And created a second script-es6.blade.php for the different output.

```
<script>
    var calendar;
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar-{{ $id }}')
        calendar = new Calendar(calendarEl,
            {!! $options !!},
        );
        calendar.render();
    });
</script>
```
